server:
  port: 8761

eureka:
  instance:
    hostname: lon1
  client:
    registerWithEureka: true # 注册中心之间的相互注册实现到高可用
    fetchRegistry: true # 注册中心之间的相互注册实现到高可用
    serviceUrl:
      defaultZone: http://lon2:8762/eureka/,http://lon3:8763/eureka/
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka-server
